[package]
name = "crab-process"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Child process management for Crab Code"

[dependencies]
crab-utils.workspace = true
crab-core.workspace = true
crab-sandbox.workspace = true
tokio.workspace = true
sysinfo.workspace = true

[dev-dependencies]

[lints]
workspace = true
